org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

mod_id=ccstudio
mod_name=CC: Studio
mod_license=PolyForm Noncommercial 1.0.0 with additional terms (see LICENSE)
mod_version=1.0.0
mod_group_id=dev.alessiodam.mcmods.ccstudio
mod_authors=alessiodam
mod_description=Open a full VS Code editor in your browser for any CC: Tweaked computer. Run `code` on a computer to start a session.

common_java_version=21
common_netty_version=4.1.97.Final
common_gson_version=2.10.1
common_slf4j_version=2.0.9
jspecify_version=1.0.0

extension_package_manager=auto
